GCOV_PROFILE := y
nvhost-objs = \
	nvhost_acm.o \
	nvhost_syncpt.o \
	nvhost_cdma.o \
	nvhost_cpuaccess.o \
	nvhost_intr.o \
	nvhost_channel.o \
	nvhost_job.o \
	dev.o \
	bus.o \
	debug.o

obj-$(CONFIG_TEGRA_GRHOST_ICS) += mpe/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += gr3d/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += t20/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += nvhost.o
