GCOV_PROFILE := y
nvhost-objs = \
	nvhost_acm.o \
	nvhost_syncpt.o \
	nvhost_cdma.o \
	nvhost_intr.o \
	nvhost_channel.o \
	nvhost_job.o \
	bus.o \
	dev.o \
	debug.o \
	bus_client.o

obj-$(CONFIG_TEGRA_GRHOST_ICS) += mpe/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += gr3d/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += host1x/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += t20/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += dsi/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += gr2d/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += isp/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += vi/
obj-$(CONFIG_TEGRA_GRHOST_ICS) += nvhost.o
