#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_SAMSUNG_PHONE_TTY)		+= cdma_dpram/
obj-$(CONFIG_SAMSUNG_LTE_MODEM_BOOTLOADER)	+= lte_bootloader/
obj-$(CONFIG_SAMSUNG_LTE_MODEMCTL)		+= lte_modemctl/
obj-$(CONFIG_SAMSUNG_WTL_FOTA_DPRAM)		+= wtlfota_dpram/
obj-y	+= wtlfota_dpram_export/
