GCOV_PROFILE := y
obj-$(CONFIG_TEGRA_GRHOST_ICS) += host/
obj-$(CONFIG_TEGRA_DC) += dc/
obj-$(CONFIG_FB_TEGRA) += fb.o
obj-$(CONFIG_TEGRA_NVMAP) += nvmap/
obj-$(CONFIG_FB_TEGRA_CMC623)     += cmc623.o
