/*
 * arch/arm/mach-tegra/gpio-p5.h
 *
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __GPIO_P5_H
#define __GPIO_P5_H

#include "../../gpio-names.h"

/* 18-port GPIO expander */
#define GPEX_GAP			5
#define GPEX_BASE			(TEGRA_GPIO_PBB7 + GPEX_GAP + 1)

#define GPEX_GPIO_P0			(GPEX_BASE+0)
#define GPEX_GPIO_P1			(GPEX_BASE+1)
#define GPEX_GPIO_P2			(GPEX_BASE+2)
#define GPEX_GPIO_P3			(GPEX_BASE+3)
#define GPEX_GPIO_P4			(GPEX_BASE+4)
#define GPEX_GPIO_P5			(GPEX_BASE+5)
#define GPEX_GPIO_P6			(GPEX_BASE+6)
#define GPEX_GPIO_P7			(GPEX_BASE+7)
#define GPEX_GPIO_P8			(GPEX_BASE+8)
#define GPEX_GPIO_P9			(GPEX_BASE+9)
#define GPEX_GPIO_P10			(GPEX_BASE+10)
#define GPEX_GPIO_P11			(GPEX_BASE+11)
#define GPEX_GPIO_P12			(GPEX_BASE+12)
#define GPEX_GPIO_P13			(GPEX_BASE+13)
#define GPEX_GPIO_P14			(GPEX_BASE+14)
#define GPEX_GPIO_P15			(GPEX_BASE+15)
#define GPEX_GPIO_P16			(GPEX_BASE+16)
#define GPEX_GPIO_P17			(GPEX_BASE+17)

/* 
 * standard: P5 Main Real Rev0.8
 */

#if defined(CONFIG_KEYBOARD_ADP5588)
#define GPIO_HALL_INT			TEGRA_GPIO_PU5
#define GPIO_KEY_I2C_SDA		TEGRA_GPIO_PK2
#define GPIO_KEY_I2C_SCL		TEGRA_GPIO_PK3
#define GPIO_KEY_INT_N			TEGRA_GPIO_PW2
#define GPIO_KEY_RST_N			TEGRA_GPIO_PI7
#endif


#define GPIO_GPIO_RST			TEGRA_GPIO_PO1
#define GPIO_MAG_I2C_SCL		TEGRA_GPIO_PO2
#define GPIO_CP_ON			TEGRA_GPIO_PO3 
#define GPIO_MAG_I2C_SDA		TEGRA_GPIO_PO4
#define GPIO_PHONE_ACTIVE		TEGRA_GPIO_PO5
#define GPIO_IFCONSENSE			TEGRA_GPIO_PO6
#define GPIO_FUEL_I2C_SCL		TEGRA_GPIO_PO7
#define GPIO_FUEL_I2C_SDA		TEGRA_GPIO_PO0
#define GPIO_LIGHT_I2C_SCL		TEGRA_GPIO_PY0
#define GPIO_GPIO_I2C_SCL		TEGRA_GPIO_PY1
#define GPIO_LIGHT_I2C_SDA		TEGRA_GPIO_PY2
#define GPIO_GPIO_I2C_SDA		TEGRA_GPIO_PY3
#define GPIO_HSIC_EN			TEGRA_GPIO_PV0 
#define GPIO_PDA_ACTIVE			TEGRA_GPIO_PV1 
#define GPIO_REMOTE_SENSE_IRQ		TEGRA_GPIO_PV2
#define GPIO_EAR_SEND_END		TEGRA_GPIO_PV3
#define GPIO_FUEL_ALRT			TEGRA_GPIO_PV6
#define GPIO_CAM_PMIC_SCL		TEGRA_GPIO_PB2
#define GPIO_LVDS_N_SHDN		TEGRA_GPIO_PC1
#define GPIO_IMAGE_I2C_SCL		TEGRA_GPIO_PC6
#define GPIO_USB_SEL1			TEGRA_GPIO_PZ2
#define GPIO_USB_SEL2			TEGRA_GPIO_PN5
#define GPIO_IMA_N_RST			TEGRA_GPIO_PN4
#define GPIO_CAM_PMIC_SDA		TEGRA_GPIO_PN6
#define GPIO_HDMI_HPD			TEGRA_GPIO_PN7
#define GPIO_IMA_BYPASS			TEGRA_GPIO_PZ4
#define GPIO_IMA_SLEEP			TEGRA_GPIO_PW0
#define GPIO_GPS_CNTL			TEGRA_GPIO_PV7 
#define GPIO_IMAGE_I2C_SDA		TEGRA_GPIO_PZ3
#define GPIO_BT_nRST			TEGRA_GPIO_PW1
#define GPIO_CAM_F_nRST			TEGRA_GPIO_PT4 
#define GPIO_CAM_F_STANDBY		TEGRA_GPIO_PD5
#define GPIO_AK8975_INT 		TEGRA_GPIO_PBB1		/* GPIO_MSENSE_IRQ */
#define GPIO_CAM_L_nRST			TEGRA_GPIO_PD2  
#define GPIO_MLCD_ON			TEGRA_GPIO_PD0
#define GPIO_EXT_WAKEUP			TEGRA_GPIO_PA0
#define GPIO_HDMI_LOGIC_I2C_SCL		TEGRA_GPIO_PJ6
#define GPIO_HDMI_LOGIC_I2C_SDA		TEGRA_GPIO_PJ5
#define GPIO_GPS_UART_TXD		TEGRA_GPIO_PU0
#define GPIO_GPS_UART_RXD		TEGRA_GPIO_PU1
#define GPIO_GPS_UART_CTS		TEGRA_GPIO_PU2
#define GPIO_GPS_UART_RTS		TEGRA_GPIO_PU3
#define GPIO_MOTOR_PWM			TEGRA_GPIO_PW5
#define GPIO_TA_nCONNECTED		TEGRA_GPIO_PU6
#define GPIO_MOTOR_EN			TEGRA_GPIO_PR2
#define GPIO_BT_WAKE			TEGRA_GPIO_PR3
#define GPIO_IPC_SLAVE_WAKEUP		TEGRA_GPIO_PR4
#define GPIO_SIM_DETECT			TEGRA_GPIO_PS0
#define GPIO_DOCK_INT			TEGRA_GPIO_PS2
#define GPIO_HSIC_SUS_REQ		TEGRA_GPIO_PQ0
#define GPIO_WLAN_EN			TEGRA_GPIO_PQ2
#define GPIO_RESET_REQ_N		TEGRA_GPIO_PQ3 
#define GPIO_IMA_PWREN			TEGRA_GPIO_PQ4
#define GPIO_HSIC_ACTIVE_STATE		TEGRA_GPIO_PQ5 
#define GPIO_CODEC_I2C_SDA		TEGRA_GPIO_PZ5
#define GPIO_TA_nCHG			TEGRA_GPIO_PK5
#define GPIO_MPU_INT			TEGRA_GPIO_PK6
#define GPIO_V_ACCESSORY_5V		TEGRA_GPIO_PU4
#define GPIO_nTHRM_IRQ			TEGRA_GPIO_PU5
#define GPIO_MLCD_ON1			TEGRA_GPIO_PX0
#define GPIO_CP_RST			TEGRA_GPIO_PX1
#define GPIO_ADC_I2C_SCL		TEGRA_GPIO_PX2
#define GPIO_ADC_I2C_SDA		TEGRA_GPIO_PX3
#define GPIO_TA_EN			TEGRA_GPIO_PX4
#define GPIO_CODEC_LDO_EN		TEGRA_GPIO_PX5
#define GPIO_TOUCH_INT			TEGRA_GPIO_PX6
#define GPIO_UART_SEL			TEGRA_GPIO_PX7
#define GPIO_IPC_HOST_WAKEUP		TEGRA_GPIO_PW2
#define GPIO_DET_3_5			TEGRA_GPIO_PW3
#define GPIO_ACCESSORY_INT		TEGRA_GPIO_PI5
#define GPIO_MHL_INT			TEGRA_GPIO_PI7
#define GPIO_BT_EN			TEGRA_GPIO_PJ0
#define GPIO_TOUCH_EN			TEGRA_GPIO_PJ2
#define GPIO_MOTOR_I2C_SCL		TEGRA_GPIO_PK3
#define GPIO_BL_RESET			TEGRA_GPIO_PR5
#define GPIO_ACC_EN			TEGRA_GPIO_PR6
#define GPIO_MOTOR_I2C_SDA		TEGRA_GPIO_PK2
#define GPIO_HW_REV4			TEGRA_GPIO_PG0
#define GPIO_HW_REV3			TEGRA_GPIO_PG1
#define GPIO_HW_REV2			TEGRA_GPIO_PG2
#define GPIO_HW_REV1			TEGRA_GPIO_PG3
#define GPIO_CP_DUMP_INT		TEGRA_GPIO_PH1 
#define GPIO_TOUCH_ID			TEGRA_GPIO_PH2 
#define GPIO_IPC_TXD			TEGRA_GPIO_PJ7
#define GPIO_IPC_RXD			TEGRA_GPIO_PB0
#define GPIO_THRM_I2C_SCL		TEGRA_GPIO_PB1
#define GPIO_CURR_ADJ			TEGRA_GPIO_PB5
#define GPIO_BT_HOST_WAKE		TEGRA_GPIO_PB6
#define GPIO_THRM_I2C_SDA		TEGRA_GPIO_PK7
#define GPIO_CODEC_I2C_SCL		TEGRA_GPIO_PI0
#define GPIO_WLAN_HOST_WAKE		TEGRA_GPIO_PC7
#define GPIO_USB_RECOVERY		TEGRA_GPIO_PI1
#if defined(CONFIG_TOUCHSCREEN_MELFAS)
#define GPIO_TSP_SDA		TEGRA_GPIO_PC5
#define GPIO_TSP_SCL		TEGRA_GPIO_PC4
#endif

#if defined(CONFIG_TDMB) || defined(CONFIG_TDMB_MODULE)
#define GPIO_TDMB_EN			TEGRA_GPIO_PR7
#define GPIO_TDMB_RST			TEGRA_GPIO_PS1
#define GPIO_TDMB_INT			TEGRA_GPIO_PH0
#define GPIO_TDMB_SPI_CS       		TEGRA_GPIO_PBB5
#define GPIO_TDMB_SPI_CLK       	TEGRA_GPIO_PBB4
#define GPIO_TDMB_SPI_MOSI      	TEGRA_GPIO_PT2
#define GPIO_TDMB_SPI_MISO      	TEGRA_GPIO_PT3
#endif

/* GPIO Expander */
#define GPIO_ACCESSORY_EN		GPEX_GPIO_P3
#define GPIO_ISP_INT			GPEX_GPIO_P4	/* 3M_STBY */
#define GPIO_CAM_EN			GPEX_GPIO_P6
#define GPIO_EAR_MICBIAS_EN		GPEX_GPIO_P7
#define GPIO_OTG_EN			GPEX_GPIO_P8
#define GPIO_GPS_PWR_EN			GPEX_GPIO_P9
#define GPIO_GPS_N_RST			GPEX_GPIO_P10
#define GPIO_MHL_RST			GPEX_GPIO_P11
#define GPIO_HDMI_EN1			GPEX_GPIO_P12
#define GPIO_CAM_MOVIE_EN		GPEX_GPIO_P13
#define GPIO_CAM_FLASH_EN		GPEX_GPIO_P14
#define GPIO_MICBIAS_EN			GPEX_GPIO_P15
#define GPIO_LIGHT_SENSOR_DVI		GPEX_GPIO_P16	/* ALC_nRST */


/* rev 0.8
 * #define GPIO_BL_RESET		TEGRA_GPIO_PK4
 * #define GPIO_PEN_PDCT		TEGRA_GPIO_PR6
 * #define GPIO_PEN_SLP			TEGRA_GPIO_PB7
 * #define GPIO_PEN_IRQ			TEGRA_GPIO_PH3
 */

/* rev0.6 ~ rev0.7
 * #define GPIO_HDMI_I2C_SCL		TEGRA_GPIO_PH1 
 * #define GPIO_HDMI_I2C_SDA		TEGRA_GPIO_PH2 
 * #define GPIO_EWRITING_EN		GPEX_GPIO_P17
 */


/* rev0.4 ~ rev0.5
 * GPIO_GPIO_INT			TEGRA_GPIO_PU5
 * GPIO_PEN_I2C_SCL			TEGRA_GPIO_PH1
 * GPIO_PEN_I2C_SDA			TEGRA_GPIO_PH2 
 * GPIO_BT_HOST_WAKE			TEGRA_GPIO_PN7
 * GPIO_MLCD_ON				TEGRA_GPIO_PI4
 * GPIO_T_FLASH_DETECT			GPEX_GPIO_P0
 * GPIO_HDMI_HPD			GPEX_GPIO_P1
 * GPIO_FUEL_ALRT			GPEX_GPIO_P2
 * GPIO_nTHRM_IRQ			GPEX_GPIO_P3
 * GPIO_CURR_ADJ			GPEX_GPIO_P5
 * GPIO_ACCESSORY_EN			GPEX_GPIO_P8  (GPIO_OTG_EN)
 */



/* usb worker must move other location*/
typedef enum
{
	USB_SEL_AP_USB = 0,
	USB_SEL_CP_USB,
	USB_SEL_ADC
} usb_path_type;


#endif  /* __GPIO_P5_H */
